# Load the rubocop-rspec gem
require: rubocop-rspec

Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'

#################
# [i] Overrides #
#################

RSpec/DescribedClass:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  # Mapping from undesired method to desired_method
  # e.g. to use `detect` over `find`:
  #
  # CollectionMethods:
  #   PreferredMethods:
  #     find: detect
  PreferredMethods:
    reduce: 'inject'
    find: 'detect'
    each_with_index: 'each.with_index'

# Align ends correctly.
EndAlignment:
  EnforcedStyleAlignWith: variable

LineLength:
  Max: 200

SignalException:
  EnforcedStyle: only_raise

SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

BracesAroundHashParameters:
  EnforcedStyle: context_dependent

StringLiterals:
  EnforcedStyle: double_quotes

#################
# Disabled cops #
#################
Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false

# HABTM still has a place.
# http://collectiveidea.com/blog/archives/2014/08/11/has_and_belongs_to_many-isnt-dead/
Rails/HasAndBelongsToMany:
  Enabled: false

# RSpec examples are ok if they're long.
# Explicitness is better than cleverness in tests.
RSpec/ExampleLength:
  Enabled: false