name: 'Buildlight'
description: 'Notify Buildlight of workflow status'
author: Daniel Morrison (@danielmorrison), [i] Collective Idea
runs:
  using: "composite"
  steps:
    - name: Webhook
      uses: joelwmale/webhook-action@448a17bf857ead98546cfbdbe3b9d4cf979dda95
      with:
        url: https://buildlight.collectiveidea.com/
        body: '{"status": "${{ github.event.workflow_run.conclusion }}", "repository": "${{ github.repository }}"}'
