name: 'Buildlight'
description: 'Notify Buildlight of workflow status'
author: Daniel Morrison (@danielmorrison), [i] Collective Idea
runs:
  using: "composite"
  steps:
    - name: Webhook
      uses: joelwmale/webhook-action@2c43ebbef8b9c5e5ea27cd65dfdeac58f90e7e29
      with:
        url: https://buildlight.collectiveidea.com/
        body: '{"status": "${{ github.event.workflow_run.conclusion }}", "repository": "${{ github.repository }}"}'
