app = 'buildlight'
primary_region = 'iad'

[build]

[env]
  HOST = 'buildlight.collectiveidea.com'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    timeout = '2s'
    path = '/up'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
