version: 2
jobs:
  build:
    working_directory: ~/buildlight
    environment:
      RAILS_ENV: test
    docker:
    - image: circleci/ruby:2.5.3-node-browsers
    steps:
    - checkout
    - run: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
    - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
        --jobs=4 --retry=3 '
    - run: |-
        mkdir -p config && echo 'test:
          database: circle_ruby_test
          adapter: postgresql
          encoding: unicode
          pool: 15
          username: ubuntu
          host: localhost
        ' > config/database.yml
    - run:
        command: bundle exec rake db:create db:schema:load --trace
    - run:
        command: bundle exec rspec --color --require spec_helper --format progress spec
