version: 2
jobs:
  build:
    working_directory: ~/buildlight
    environment:
      RAILS_ENV: test
    docker:
    - image: cimg/ruby:3.2.1-node
      environment:
        PGHOST: localhost
        PGUSER: buildlight
        RAILS_ENV: test
    - image: postgres:10.1-alpine
      environment:
        POSTGRES_USER: buildlight
        POSTGRES_DB: buildlight_test
        POSTGRES_PASSWORD: ""
    steps:
    - checkout
    - run: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
    - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
        --jobs=4 --retry=3 '
    - run:
        name: Install Yarn Dependencies
        command: yarn install --cache-folder ~/.yarn-cache
    - run: |-
        mkdir -p config && echo 'test:
          database: buildlight_test
          adapter: postgresql
          encoding: unicode
          pool: 15
          username: buildlight
          host: localhost
        ' > config/database.yml
    - run:
        command: bundle exec bin/setup
    - run:
        command: yarn build:css
    - run:
        command: bundle exec rake
notify:
  webhooks:
    - url: https://buildlight.collectiveidea.com
