name: CI

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: correcthorsebatterystaple
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: postgres://test:correcthorsebatterystaple@localhost:5432/test
      RAILS_ENV: test
      RUBYOPT: --enable=frozen-string-literal

    steps:
    - uses: actions/checkout@master

    # setup-ruby can infer the Ruby version
    - name: Create .ruby-version based on Gemfile
      run: grep -oP '^ruby .\K\d+\.\d+\.\d+' Gemfile > .ruby-version

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'npm'

    - name: NPM Install
      run: npm ci

    - name: App Setup
      run: bin/setup

    - name: Build CSS
      run: npm run build:css

    - name: Standard
      run: bundle exec rake standard

    - name: Run Tests
      run: bundle exec rspec --format progress --color
